<a href="https://colab.research.google.com/github/boramkim0514/hw/blob/main/day12_pm_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
pop = pd.read_csv('/content/sample_data/pop.csv', header=3)

In [4]:
type(pop)

pandas.core.frame.DataFrame

In [5]:
pop

         기간    자치구       소계      남자  ...    여자.6     계.4    남자.7    여자.7
0   2021.03  서울특별시  151,617  73,389  ...  28,887  -6,216  -4,453  -1,763
1   2021.03    종로구    2,644   1,266  ...     444     -53     -87      34
2   2021.03     중구    1,966     949  ...     352    -178    -126     -52
3   2021.03    용산구    4,462   2,111  ...     674     580     169     411
4   2021.03    성동구    4,656   2,282  ...     800    -385    -293     -92
5   2021.03    광진구    5,432   2,551  ...   1,093    -395    -224    -171
6   2021.03   동대문구    5,640   2,802  ...   1,007      96      36      60
7   2021.03    중랑구    5,129   2,534  ...   1,043    -523    -326    -197
8   2021.03    성북구    6,761   3,180  ...   1,162    -188    -206      18
9   2021.03    강북구    3,802   1,865  ...     698    -484    -256    -228
10  2021.03    도봉구    3,754   1,831  ...     777    -565    -291    -274
11  2021.03    노원구    6,372   3,075  ...   1,301    -677    -404    -273
12  2021.03    은평구    6,021   2,859  ...   1,425    -630    -372    -258
13  2021.03   서대문구    4,930   2,252  ...     920    -160    -203      43
14  2021.03    마포구    6,599   3,104  ...   1,158    -187     -58    -129
15  2021.03    양천구    6,162   3,048  ...     987    -240    -208     -32
16  2021.03    강서구    9,737   4,708  ...   1,732     246     -25     271
17  2021.03    구로구    5,175   2,591  ...   1,231    -246     -94    -152
18  2021.03    금천구    3,388   1,732  ...     784     -52     -34     -18
19  2021.03   영등포구    6,206   3,027  ...   1,190     -14    -102      88
20  2021.03    동작구    7,245   3,504  ...   1,270     389     178     211
21  2021.03    관악구    9,971   5,001  ...   1,991    -277    -192     -85
22  2021.03    서초구    6,102   2,914  ...   1,190  -1,025    -478    -547
23  2021.03    강남구    8,868   4,298  ...   1,712  -1,277    -656    -621
24  2021.03    송파구   10,653   5,079  ...   2,496  -2,090  -1,151    -939
25  2021.03    강동구    9,942   4,826  ...   1,450   2,119     950   1,169

[26 rows x 26 columns]

In [6]:
pop1 = pop.iloc[1:, [1,3,4,6,7]]
pop1.columns=['자치구', '전입남자', '전입여자', '전출남자', '전출여자']

In [7]:
pop1['총전입'] = pop1['전입남자'] + pop1['전입여자']
pop1['총전출'] = pop1['전출남자'] + pop1['전출여자']

In [8]:
pop1

     자치구   전입남자   전입여자   전출남자   전출여자         총전입         총전출
1    종로구  1,266  1,378  1,353  1,344  1,2661,378  1,3531,344
2     중구    949  1,017  1,075  1,069    9491,017  1,0751,069
3    용산구  2,111  2,351  1,942  1,940  2,1112,351  1,9421,940
4    성동구  2,282  2,374  2,575  2,466  2,2822,374  2,5752,466
5    광진구  2,551  2,881  2,775  3,052  2,5512,881  2,7753,052
6   동대문구  2,802  2,838  2,766  2,778  2,8022,838  2,7662,778
7    중랑구  2,534  2,595  2,860  2,792  2,5342,595  2,8602,792
8    성북구  3,180  3,581  3,386  3,563  3,1803,581  3,3863,563
9    강북구  1,865  1,937  2,121  2,165  1,8651,937  2,1212,165
10   도봉구  1,831  1,923  2,122  2,197  1,8311,923  2,1222,197
11   노원구  3,075  3,297  3,479  3,570  3,0753,297  3,4793,570
12   은평구  2,859  3,162  3,231  3,420  2,8593,162  3,2313,420
13  서대문구  2,252  2,678  2,455  2,635  2,2522,678  2,4552,635
14   마포구  3,104  3,495  3,162  3,624  3,1043,495  3,1623,624
15   양천구  3,048  3,114  3,256  3,146  3,0483,114  3,2563,146
16   강서구  4,708  5,029  4,733  4,758  4,7085,029  4,7334,758
17   구로구  2,591  2,584  2,685  2,736  2,5912,584  2,6852,736
18   금천구  1,732  1,656  1,766  1,674  1,7321,656  1,7661,674
19  영등포구  3,027  3,179  3,129  3,091  3,0273,179  3,1293,091
20   동작구  3,504  3,741  3,326  3,530  3,5043,741  3,3263,530
21   관악구  5,001  4,970  5,193  5,055  5,0014,970  5,1935,055
22   서초구  2,914  3,188  3,392  3,735  2,9143,188  3,3923,735
23   강남구  4,298  4,570  4,954  5,191  4,2984,570  4,9545,191
24   송파구  5,079  5,574  6,230  6,513  5,0795,574  6,2306,513
25   강동구  4,826  5,116  3,876  3,947  4,8265,116  3,8763,947